name: Publish to NPM

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun i -g npm
      - run: bun ci
      - run: bun run build
      - run: npm publish
